### ISSUE TITLE
demo with content?

### ISSUE THREAD

**Issue by avibodha** [AcroMedia/commerce-demo#1]
Could you put up an installation with the demo content shown in Urban Hipster? That would help in understanding how to get started with commerce. Like the Kickstart install with demo content.

**Comment by smmccabe** [comment]
We're building a proper demo version, but it's still a few weeks away, as setting up all the content to install nicely is not as easy as you'd think. I could add a simple db dump to the repo if people were interested in the short term.

**Comment by avibodha** [comment]
I think that would be helpful to see how set up blocks etc for us new to drupal 8 and commerce 2. thanks for your work on this! a working demo that we can take apart and see how it's set up is a good learning tool.

**Comment by avibodha** [comment]
thanks!
