### ISSUE TITLE
Use recommended products more

### ISSUE THREAD

**Issue by bojanz** [AcroMedia/commerce-demo#13]
This functionality is great, but it's only visible on the custom-mason-jar product, making it really easy to miss. I'd add random recommended products to each product, making the functionality more visible.

**Comment by MikeAcro** [comment]
Yes, good call. Currently, this is set up for our people to demo and so they know where to go. But you're right, others should also be able to find it easily, too. I'll work this in with the other content update issues when I get to them.

**Comment by MikeAcro** [comment]
All products now include recommended products.
