### ISSUE TITLE
Ensure all images are GPL compatible

### ISSUE THREAD

**Issue by bojanz** [AcroMedia/commerce-demo#14]
The images need to be public domain or GPL so that they can be shared on drupal.org, in distributions, etc.

**Comment by MikeAcro** [comment]
Yes. This is a planned change that will be done soon (along with #12 and possibly #15).

**Comment by MikeAcro** [comment]
All images and icons on the site are now GPL compatible or something we created with the intention to give away with the demo.

The photos are from unsplash.com. There's a credit to them in the footer and in the README.md.

https://unsplash.com/license
