### ISSUE TITLE
Replace the "default" product/variation type with a "simple" one.

### ISSUE THREAD

**Issue by bojanz** [AcroMedia/commerce-demo#15]
Right now we rely on the Commerce-created "default" product and variation type, for products that have no attributes. When moving the types to a module "default" won't be exportable cause it belongs to Commerce. This also prevents us from having custom settings for it in the future (such as enabling single-variation mode once it gets added).

I suggest creating our own "simple" product/variation type and moving the default products to that.
I've done that as a part of the commerce_demo module work, so we can wait until adopting the module if the task itself is too time consuming at this point.

**Comment by MikeAcro** [comment]
Ok. Good to know. I'll look into this. In the meantime, keep me updated if the module is done before I get to this. Thanks, Bojanz.

**Comment by MikeAcro** [comment]
This has been changed. No products use the Default product/variation type anymore. Instead, there is now a Basic product/variation type. I also included better descriptions for the user who would be adding content to explain the product types.
