### ISSUE TITLE
Patch does not apply apply after core update 8.4.5

### ISSUE THREAD

**Issue by MrPaulDriver** [AcroMedia/commerce-demo#17]
After applying today's core update one of the patches fails to apply .

 - Applying patches for drupal/commerce

   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/adjustment_label_how-2770731-20.patch

**Comment by MikeAcro** [comment]
Thanks for letting me know, Paul.

It looks like there's a new patch available [here](https://www.drupal.org/project/commerce/issues/2770731#comment-12480612).

I haven't tested that yet, and probably won't be able to it until next week at the soonest. In the meantime, you can manually update the composer.json with that one.

**Comment by MikeAcro** [comment]
I pushed some updates today. Mainly core and module updates.

I'm going to close this since the update includes the latest patch I linked to, which appears to be applying clean.
