### ISSUE TITLE
 Unable to find template

### ISSUE THREAD

**Issue by smengar05** [AcroMedia/commerce-demo#19]
I have next problem
[14-Mar-2018 17:51:24 America/Chicago] Uncaught PHP Exception Twig_Error_Loader: "Template "/commerce-demo-master/web/themes/custom/commerce_2_demo/templates/pages/includes/site_header.html.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "/commerce-demo-master/web/themes/custom/commerce_2_demo/templates/pages/includes/site_header.html.twig" in the Drupal theme registry.) in "themes/custom/commerce_2_demo/templates/pages/page--front.html.twig" at line 13." at /var/www/html/commerce-demo-master/vendor/twig/twig/lib/Twig/Loader/Chain.php line 129

I was trying to clear cache with Drupal UI, but the problem continue. You had a Issue Closed.

Thank.

**Comment by MikeAcro** [comment]
That template does exist and you can confirm by finding it at that path, so I suspect you're still seeing a caching issue.

However, if flushing cache isn't solving it for you, maybe there is a deeper problem with the way the template is being included. A quick Google search reveals a few different methods that maybe you could try and report back.

`{% include 'site_header.html.twig' %}`
[Source](https://drupal.stackexchange.com/questions/141066/include-a-partial-template/141104#141104)

`{% include directory ~ '/templates/pages/includes/site_header.html.twig' %}`
[Source](https://www.drupal.org/project/drupal/issues/2817553)

**Comment by smengar05** [comment]
Thank , I'll look.

**Comment by MikeAcro** [comment]
Btw, I just pushed some updates today. I don't think it would solve the problem you're seeing, but just thought you might want to know since you're setting up the demo now. 

The update mainly just updating core to 8.5.0 as well as some other modules. There's a new database dump.

**Comment by MikeAcro** [comment]
I still think you're having a caching issue, but in any case, I just did a quick test on my local site.

These are includes that worked for me.
`{% include directory ~ '/templates/pages/includes/site_header.html.twig' %}`
`{% include base_path ~ directory ~ '/templates/pages/includes/site_header.html.twig' %}`

The following did not.
`{% include 'site_header.html.twig' %}`
`{% include '/templates/pages/includes/site_header.html.twig' %}`

**Comment by smengar05** [comment]
I've changed this {% include directory ~ '/templates/pages/includes/site_header.html.twig' %} all include, the result is the same. 

I prefer wait for update to drupal 8.5.0.

Thank you.

**Comment by MikeAcro** [comment]
Hello again,

The current code and database dump is Drupal 8.5.0, so you can reclone/download and use the provided database in the 'dumps' directory.

However, maybe try doing this first. From the command line, go into the `web` directory and run `../vendor/drush/drush/drush cr`.

Drush 9 is packaged in with the project and running that will clear caches. Maybe there's some strange hangup between your way of clearing caches and the site. It's a shot in the dark, but something quick to try.

**Comment by smengar05** [comment]
I'm upgrading to drupal 8.5.0 and i have the same problem with loading
include files in the themes.

El 20 mar. 2018 3:49 p. m., "Mike Hubbard" <notifications@github.com>
escribió:

Hello again,

The current code and database dump is Drupal 8.5.0, so you can
reclone/download and use the provided database in the 'dumps' directory.

However, maybe try doing this first. From the command line, go into the web
directory and run ../vendor/drush/drush/drush cr.

Drush 9 is packaged in with the project and running that will clear caches.
Maybe there's some strange hangup between your way of clearing caches and
the site. It's a shot in the dark, but something quick to try.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AcroMedia/commerce-demo/issues/19#issuecomment-374625572>,
or mute the thread

**Comment by MikeAcro** [comment]
Ahh, that's annoying. I'll leave this issue open in case something comes up that could fix the issue you're experiencing, but I'm really not sure why you're having these problems and unfortunately, I can't spend much time on individual support. If I stumble across potential solutions, I'll post them here.

**Comment by 99gs300tw** [comment]
I am unable to access the demote site at all. After running composer on a local xampp build, I've noticed the drupal 8 core files were installed in web subfolder. Could this be the cause?

**Comment by MikeAcro** [comment]
If your server config is looking for wwwroot instead of web, that could be your problem.

If you haven't done so yet, check the README.md for some setup instructions.

**Comment by 99gs300tw** [comment]
I've followed the instructions on this and it is now working. Thanks https://www.drupal.org/forum/support/post-installation/2016-06-22/d8-how-to-use-drupal-8-in-a-subfolder#comment-12120503

**Comment by 99gs300tw** [comment]
Hi Mike,

Just seen the video on the Enhanced Product UH+ Axe, that is pretty slick. Particularly product variation and bundling the products with options. Are the codes that you were using to build the demo available for download? or is there any existing modules that does bundling for commerce 2.x yet?

Thanks in advance.

**Comment by MikeAcro** [comment]
Thanks!

When that page was built there was no module available, so instead I had to do some interesting stuff in the .theme file. You can [take a look](https://github.com/AcroMedia/commerce-demo/blob/master/web/themes/custom/commerce_2_demo/commerce_2_demo.theme) there. I added a product reference field and a custom submit handler. There's also a radio checkbox that is used to toggle whether or not the custom submit handler is used. If it is, then the referenced product gets added to the cart along with the axe.

This was a pretty quick and dirty solution, so I wouldn't recommend doing it that way. There are a few modules out now (linked below) that may be a better solutions. I think the first one is furthest along.

https://www.drupal.org/project/commerce_pado
https://www.drupal.org/project/commerce_product_bundle
