### ISSUE TITLE
I have not been able to install the site on my local computer

### ISSUE THREAD

**Issue by jhonatanfdez** [AcroMedia/commerce-demo#20]
I have followed the indicated steps, but I have not been able to install it.
They could make a detailed video of how to install it with php7.0

**Comment by MikeAcro** [comment]
Hi jhonatenfdez,

A video is a good idea. I'll add it to my list of things to do, but don't expect it any time soon. If I do get to it, it would also be made based on Drupal 8's recommended system requirements ([which includes PHP 7.1](https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements)).

Your best bet is to update your PHP to 7.1.

**Comment by jch-Github** [comment]
Been using PHP 7.2 for a while now with D8 in a local home-brew Apache
stack. Recently went from PHP 7.2.2 to PHP 7.2.4 with no problems. I would
skip 7.1 If you have not installed it yet. Swapping out PHP versions is
very quick and painless.

**Comment by MikeAcro** [comment]
Agreed. Thanks for your input!
