### ISSUE TITLE
The website encountered an unexpected error

### ISSUE THREAD

**Issue by TommyTran1** [AcroMedia/commerce-demo#24]
Twig_Error_Loader</em>: Template &quot;/commerce-demo/web/themes/custom/commerce_2_demo/templates/pages/includes/site_header.html.twig&quot; is not defined in &quot;themes/custom/commerce_2_demo/templates/pages/page--front.html.twig&quot; at line 13

**Comment by MikeAcro** [comment]
This has been reported before and it appears that it is just a caching issue. Others have reported fixing it by clearing caches through the Drupal UI (not using Drush). You can see the previous issues here:

https://github.com/AcroMedia/commerce-demo/issues/8
https://github.com/AcroMedia/commerce-demo/issues/9
https://github.com/AcroMedia/commerce-demo/issues/19
