### ISSUE TITLE
Add On Products

### ISSUE THREAD

**Issue by istimf** [AcroMedia/commerce-demo#30]
add On Product is not rendered .. i set up  a field Add On Products in commerce -configuration-product type -- and set up entities reference as Product ..-- then i added some product to form a bundle and nothing is showing up in the front -end .. can you please help me how to make it ? thank you.

**Comment by istimf** [comment]
the flag bundle availaible is there , but when i open the product , no bundle is showing up..

**Comment by MikeAcro** [comment]
Hi istimf. Unfortunately, I'm not able to provide this level of user-specific support.

I would recommend that you check out the [module project page](https://www.drupal.org/project/commerce_pado) for configuration instructions. If that doesn't help, you could look at [this page](https://docs.drupalcommerce.org/commerce2/getting-started/getting-help) on getting help from the Drupal community. The commerce Slack channel is a great place for support.

**Comment by istimf** [comment]
thank you so much ! i saw my mistake .. it was here .
. Select 'Add to cart form with add-ons' for the Variations field  in 
'Manage display' tab.

**Comment by MikeAcro** [comment]
Right on! Glad to hear you got it sorted out.
