### ISSUE TITLE
UH+ Axe product is missing in this installation

### ISSUE THREAD

**Issue by montesajudy** [AcroMedia/commerce-demo#34]
Great demo, however the axe product showcase is not included in this installation.
It's not in the product type, no product attributes, etc.

**Comment by Hubbz** [comment]
Hi @montesajudy . You are correct. The database that is provided is that same that is used on https://commerce.acromedia.com. This is a closer representation of Drupal Commerce out-of-the-box and this is what we share with the community.

The UH Axe product (as seen on https://commerceplus.acromedia.com), as well as some other more custom products and features, are not part of that database. These are things that our sales teams use to showcase some of the more custom work Acro Media can do with Drupal Commerce. This is an internal sales tool and so we don't give that away.

Now with that said, both sites share the same code base so you do have access to the templates, just not the configuration.
