### ISSUE TITLE
Is admin access allowed?

### ISSUE THREAD

**Issue by MrPaulDriver** [AcroMedia/commerce-demo#4]
It would be great to take a look at what you have done with the backend from a sitebuilder / store owner perspective.

Is admin access allowed for the demo?

BTW. This is brilliant work. Inspirational. Thank you

**Comment by MikeAcro** [comment]
@MrPaulDriver - you can login to the demo at http://commercedemo.acromedia.com using demoadmin/demoadmin . The database does reset every night, so any changes you make will be reverted then.

Glad you're liking it! Cheers.
