### ISSUE TITLE
Up to date database dump?

### ISSUE THREAD

**Issue by MrPaulDriver** [AcroMedia/commerce-demo#5]
Would it be possible to include a database dump for Drupal 8.4

**Comment by MikeAcro** [comment]
Yes, I'm aiming to get a new dump next week. In the meantime, if the environment you're using isn't currently running PHP 7.1, you'll want to allow for it.

**Comment by MikeAcro** [comment]
Hi @MrPaulDriver .  Site has been updated to 8.4 and a new DB provided. I also updated the project README.md . Please give it a read. Thanks.

**Comment by MrPaulDriver** [comment]
Thank you Mike

---
Paul Driver
Ilkley, West Yorkshire, UK
padriver@gmail.com
+44 7718 782828
