### ISSUE TITLE
Twig_Error_Loader with new and db installation

### ISSUE THREAD

**Issue by eurodomenii** [AcroMedia/commerce-demo#8]
Is this related to _Theme registry doesn't find templates in subfolders for self-defined theme hooks_  https://www.drupal.org/node/2817103 ?

Full log
``
a:6:{s:5:"%type";s:17:"Twig_Error_Loader";s:8:"@message";s:381:"Template "/web/themes/custom/commerce_2_demo/templates/pages/includes/site_header.html.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "/web/themes/custom/commerce_2_demo/templates/pages/includes/site_header.html.twig" in the Drupal theme registry.) in "themes/custom/commerce_2_demo/templates/pages/page--front.html.twig" at line 13.";s:9:"%function";s:32:"Twig_Loader_Chain->getCacheKey()";s:5:"%file";s:76:"/var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Loader/Chain.php";s:5:"%line";i:129;s:17:"@backtrace_string";s:6778:"#0 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Template/TwigEnvironment.php(113): Twig_Loader_Chain->getCacheKey('/web/themes/cus...')
#1 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Environment.php(424): Drupal\Core\Template\TwigEnvironment->getTemplateClass('/web/themes/cus...')
#2 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Environment->loadTemplate('/web/themes/cus...', NULL)
#3 /var/www/clients/client0/web4/web/web/sites/default/files/php/twig/5a2ca1880d61a_page--front.html.twig_9KtE-G-EXM99DaYMkiOBVAMP2/5JGT25z_VY3-hWuyv4GxsPAI9WypKi8CEbZo3SaPjNw.php(43): Twig_Template->loadTemplate('/web/themes/cus...', 'themes/custom/c...', 13)
#4 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_6d24743a78b283458b00cadff6ac17bcd7a2fea59264e8d2d3a0c2a8875846fb->doDisplay(Array, Array)
#5 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)
#7 /var/www/clients/client0/web4/web/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)
#8 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/custom/c...', Array)
#9 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('page', Array)
#10 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#11 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array)
#12 /var/www/clients/client0/web4/web/web/sites/default/files/php/twig/5a2ca1880d61a_html.html.twig_L9BMIvBp6hiGOwjn2dLIJUijn/XsCuqH9edcvlgvob6cTi2ouCQANjqmlW5BoEHtLPyMs.php(156): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#13 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_eb12ab807d22764d132df73885020fcf1191fada2205bff59b8cb30938b1f929->doDisplay(Array, Array)
#14 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /var/www/clients/client0/web4/web/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)
#16 /var/www/clients/client0/web4/web/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array)
#17 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/custom/c...', Array)
#18 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('html', Array)
#19 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#20 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array)
#21 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/Renderer.php(576): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#22 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#23 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#24 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(108): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#25 /var/www/clients/client0/web4/web/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#26 /var/www/clients/client0/web4/web/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#27 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/clients/client0/web4/web/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(182): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/clients/client0/web4/web/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(121): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/clients/client0/web4/web/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(75): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/clients/client0/web4/web/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /var/www/clients/client0/web4/web/web/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /var/www/clients/client0/web4/web/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#37 {main}";}
``
Thank you!

**Comment by MikeAcro** [comment]
Hmm. Interesting. I'll be releasing an updated demo tomorrow (probably). Maybe you could pull it down and see if you still get the same error?

**Comment by eurodomenii** [comment]
Of course. Thx!

**Comment by MikeAcro** [comment]
Hey @eurodomenii . Various were pushed up today and a new database included. Feel free to pull any time.

**Comment by MikeAcro** [comment]
As referenced by drupauler, it appears that this error can be fixed by clearing the caches via the Drupal UI. I'm going to close this issue.

> Still no major clues but when all else fails, clear all cache, which I did from the admin interface. This obviously cleared something the drush9 cr didn’t, as at that point the front end started working.
